.flake8
=> Max line leght to 100 charactes

Playwright/__init__.py, Playwright/locators/__init__.py, Playwright/locators/locatorparse.py, utest/test_locator_parse.py
=> Locator parser

.dockerignore, Dockerfile
Dockerfiles for clean environment testing.
=> Add testing Dockerfile and .dockerignore

Browser/keywords/browser_control.py, Browser/keywords/input.py, Browser/keywords/waiter.py, Browser/playwright.py, Browser/utils/time_conversion.py, utest/test_timestr_to_millisecs.py
Internal wrapper to RF timestr_to_secs to milliseconds.
=> Secs to milliseconds

.github/workflows/python-package.yml, .gitignore, Makefile, package.json
Automatically yarn install on changed package.json / yarn.lock
Add laziness to re-generating js code with webpack
Add laziness to protobuf re-generation
Add laziness to node linting
=> Makefile improvements

Makefile, node/playwright-wrapper/execution-time-decorators.ts, node/playwright-wrapper/grpc-service.ts, node/tsconfig.json
TODO: instead of logging to STDOUT write to some execution time logfile. Preferably something that can be easily parsed to a function flamegraph or something else that will show pain points
=> Add class based time spent executing decorator

yarn.lock
This reverts commit 66d0dd9e935375a1071770b78c7fc241442afcb5.
=> Revert "Fix jpeg vul"

Browser/keywords/cookie.py, atest/library/common.py, atest/test/02_Content_Keywords/cookie.robot, atest/test/keywords.resource, node/playwright-wrapper/cookie.ts, node/playwright-wrapper/grpc-service.ts, protobuf/playwright.proto
=> Add cookie

Browser/browser.py, Browser/keywords/browser_control.py, atest/test/01_Browser_Management/auto_closing.robot, atest/test/01_Browser_Management/playwright_state_getters.robot, atest/test/02_Content_Keywords/checkbox.robot, atest/test/02_Content_Keywords/click.robot, atest/test/02_Content_Keywords/keypress.robot, atest/test/02_Content_Keywords/select_lists.robot, atest/test/02_Content_Keywords/text_keywords.robot, node/playwright-wrapper/browser-control.ts, node/playwright-wrapper/playwright-state.ts
This is first version of Autoclose feature.
During this time also detected few test cases that were accidentally passing.
=> Autoclosing

Browser/keywords/getters.py, node/playwright-wrapper/getters.ts, node/playwright-wrapper/response-util.ts
Also added log massage to boolResponse responce util
=> Fixed and improved get_checkbox_state logging

Browser/keywords/evaluation.py, atest/test/05_JS_Tests/on_page_js.robot, node/playwright-wrapper/evaluation.ts, protobuf/playwright.proto
Highlight Elements does now support styles. like width, style and color of the border...
=> Highlight elements

.github/workflows/python-package.yml, Browser/__init__.py, Browser/keywords/network.py, Browser/mypy.ini, Browser/playwright.py, Browser/requirements.txt, Browser/utils/data_types.py, README.md, setup.py, tasks.py
Literal and TypedDict and cached_property
=> Add python 3.7 support through using backported 3.8 features

CORE_TEAM_AGREEMENT.md
Signed-off-by: Tatu Aalto <aalto.tatu@gmail.com>
=> Tatu agrees on the rules

Browser/assertion_engine.py, Browser/base/librarycomponent.py, Browser/browser.py, Browser/keywords/browser_control.py, atest/test/01_Browser_Management/timeout.robot, utest/test_assertion_engine.py
Mechanism to timeout assertions faster than with global timeout.
=> Retry assertions until

Browser/keywords/getters.py, Browser/keywords/waiter.py, node/playwright-wrapper/evaluation.ts, node/playwright-wrapper/getters.ts, node/playwright-wrapper/grpc-service.ts, protobuf/playwright.proto
Moved few string responses to use json response.
=> Json protobuf

Browser/assertion_engine.py, Browser/keywords/getters.py, Browser/keywords/playwright_state.py, atest/test/02_Content_Keywords/basic_getters.robot, atest/test/variables.resource, node/dynamic-test-app/static/enabled_disabled_fields_form.html
Added 
`Get Attribute Names`
`Get Classes`
=> More getters

Browser/browser.py, Browser/keywords/interaction.py, Browser/utils/data_types.py, atest/test/01_Browser_Management/Auto_Closing/auto_closing_suite_level.robot, atest/test/01_Browser_Management/device_descriptors.robot, atest/test/01_Browser_Management/hangs_setup.robot, atest/test/01_Browser_Management/timeout.robot, atest/test/02_Content_Keywords/virtual_mouse.robot, atest/test/variables.resource, node/playwright-wrapper/getters.ts
=> Dungeons&Dragons 🐉 

Browser/keywords/browser_control.py, atest/test/02_Content_Keywords/screenshot.robot, atest/test/keywords.resource
=> Embed screenshot to log.html

atest/test/02_Content_Keywords/screenshot.robot, node/playwright-wrapper/browser-control.ts
=> Test errors in screenshots

Browser/keywords/cookie.py, Browser/utils/__init__.py, Browser/utils/data_types.py, Browser/utils/meta_python.py
=> Add Cookie sameSite to Enum

CONTRIBUTING.md
Corrections/suggestions after proofreading.
=> Fixes #370

Browser/keywords/playwright_state.py, Browser/utils/meta_python.py, atest/test/01_Browser_Management/playwright_state.robot
=> Close empty contex

Browser/keywords/playwright_state.py, Browser/utils/meta_python.py, atest/test/01_Browser_Management/playwright_state.robot, node/playwright-wrapper/playwright-state.ts
=> Close empty browser

atest/test/03_Waiting/wait_for_http.robot, tasks.py
=> Fix Wait For Request

Browser/dev-requirements.txt, Browser/requirements.txt
=> Require RF 3.2.2

Browser/keywords/getters.py, atest/test/01_Browser_Management/element_selector.robot
This feels ugly but could not understand how to get it working in TS side. 
Fixes #366
=> Get Elements returns empty list when element is not found

Browser/gen_stub.py, Browser/keywords/getters.py, Browser/keywords/interaction.py, Browser/utils/__init__.py, Browser/utils/data_types.py, Browser/utils/js_utilities.py
=> Scrolling Keywords

Browser/keywords/browser_control.py, Browser/keywords/playwright_state.py, atest/test/01_Browser_Management/element_selector.robot, atest/test/01_Browser_Management/geolocation.robot, atest/test/01_Browser_Management/get_ids.robot, atest/test/keywords.resource, atest/test/variables.resource, node/dynamic-test-app/static/geolocation.html, node/playwright-wrapper/browser-control.ts, node/playwright-wrapper/grpc-service.ts, protobuf/playwright.proto
=> Geolocation

atest/test/01_Browser_Management/geolocation.robot, node/playwright-wrapper/browser-control.ts
=> Handle errors in setting geolocation

Browser/keywords/playwright_state.py, Browser/playwright.py, atest/test/01_Browser_Management/goto.robot, node/playwright-wrapper/index.ts, node/playwright-wrapper/playwright-state.ts, protobuf/playwright.proto
=> Tune env variables

Browser/keywords/network.py
=> Fixed incorect type hint and docs for Wait For Responce/Request

Browser/keywords/browser_control.py, atest/test/01_Browser_Management/goto.robot, atest/test/variables.resource, node/playwright-wrapper/browser-control.ts
=> Add timeout to Go To keyword

Browser/keywords/browser_control.py, Browser/keywords/cookie.py, Browser/keywords/device_descriptors.py, Browser/keywords/evaluation.py, Browser/keywords/getters.py, Browser/keywords/interaction.py, Browser/keywords/network.py, Browser/keywords/playwright_state.py, Browser/keywords/promises.py, Browser/keywords/waiter.py, Browser/keywords/webapp_state.py, Browser/utils/data_types.py, node/playwright-wrapper/evaluation.ts
hi @mkorpela 
I am not happy with that ugly exception catching.
But i have also not real better ideas.
Maybe that should be moved to Node side...
=> first draft of Get Element State

.github/workflows/python-package.yml, Browser/browser.py, Browser/keywords/getters.py, Browser/keywords/interaction.py, Browser/keywords/playwright_state.py, Browser/utils/__init__.py, Browser/utils/data_types.py, atest/test/01_Browser_Management/device_descriptors.robot, atest/test/02_Content_Keywords/virtual_mouse.robot, node/playwright-wrapper/playwright-state.ts
Added a generic TypedDict Converter.
Error handling could be more explicit on the incompatible types.
Please Review
=> Relative Mouse Move, defaultBrowserType, TypedDict Converter

Browser/keywords/device_descriptors.py
=> Fix link to PW docs

Browser/keywords/cookie.py, atest/test/02_Content_Keywords/cookie.robot, utest/test_cookie.py
=> Fix Get Cookie OSError

Browser/browser.py, Browser/keywords/browser_control.py, Browser/keywords/cookie.py, Browser/keywords/device_descriptors.py, Browser/keywords/evaluation.py, Browser/keywords/getters.py, Browser/keywords/interaction.py, Browser/keywords/network.py, Browser/keywords/playwright_state.py, Browser/keywords/promises.py, Browser/keywords/runonfailure.py, Browser/keywords/waiter.py, Browser/keywords/webapp_state.py, Browser/utils/__init__.py, Browser/utils/misc.py, Browser/utils/robot_booleans.py, atest/test/02_Content_Keywords/text_keywords.robot, utest/test_secrets.py
This reverts commit 8d29973695a615ab59b2c6c0dddb5f0210bd7e9c.
=> Secret vars

Browser/assertion_engine.py, Browser/browser.py, Browser/utils/misc.py, atest/test/02_Content_Keywords/screenshot.robot, utest/approved_files/test_assertion_engine.test_contains.approved.txt, utest/approved_files/test_assertion_engine.test_ends_with.approved.txt, utest/approved_files/test_assertion_engine.test_equals.approved.txt, utest/approved_files/test_assertion_engine.test_greater.approved.txt, utest/approved_files/test_assertion_engine.test_greater_or_equal.approved.txt, utest/approved_files/test_assertion_engine.test_less.approved.txt, utest/approved_files/test_assertion_engine.test_less_or_equal.approved.txt, utest/approved_files/test_assertion_engine.test_match.approved.txt, utest/approved_files/test_assertion_engine.test_not_equals.approved.txt, utest/approved_files/test_assertion_engine.test_start_with.approved.txt, utest/approved_files/test_assertion_engine.test_then.approved.txt, utest/approved_files/test_assertion_engine.test_validate.approved.txt, utest/approved_files/test_assertion_engine.test_with_assertions_polling.approved.txt, utest/approved_files/test_assertion_engine.test_without_assertions_polling.approved.txt, utest/approved_files/test_type_converter.test_type_converter.approved.txt, utest/test_assertion_engine.py, utest/test_type_converter.py
=> Type to assertion engine

Browser/playwright.py, atest/test/01_Browser_Management/device_descriptors.robot, atest/test/01_Browser_Management/element_selector.robot, atest/test/01_Browser_Management/geolocation.robot, atest/test/01_Browser_Management/goto.robot, atest/test/01_Browser_Management/grpc_overflow.robot, atest/test/01_Browser_Management/offline.robot, atest/test/01_Browser_Management/playwright_state.robot, atest/test/02_Content_Keywords/cookie.robot, atest/test/02_Content_Keywords/screenshot.robot, atest/test/03_Waiting/wait_for_element_state.robot, atest/test/03_Waiting/wait_for_function.robot, atest/test/06_Examples/open_in_another_tab.robot, atest/test/grpc_overflow.robot, node/playwright-wrapper/grpc-service.ts, node/playwright-wrapper/response-util.ts
=> Truncate grpc error messages

Browser/.flake8, Browser/entry.py, Browser/playwright.py, Browser/pyproject.toml, setup.py, tasks.py
Stop polluting user home directory with the browsers.
Closes #523
=> Install browsers in /wrapper

Browser/base/librarycomponent.py, Browser/keywords/browser_control.py, Browser/keywords/playwright_state.py, atest/test/01_Browser_Management/video.robot, atest/test/02_Content_Keywords/screenshot.robot
=> Screenshots to browser/screenshots folder when using default name

Browser/assertion_engine.py, Browser/browser.py, Browser/keywords/getters.py, Browser/keywords/playwright_state.py, Browser/keywords/webapp_state.py, atest/test/01_Browser_Management/local_storage.robot, atest/test/01_Browser_Management/playwright_state_getters.robot, atest/test/02_Content_Keywords/basic_getters.robot, atest/test/02_Content_Keywords/checkbox.robot, atest/test/02_Content_Keywords/text_keywords.robot, atest/test/02_Content_Keywords/title_should_be.robot, tasks.py
=> Assertion custom message 3

Browser/keywords/waiter.py, atest/test/03_Waiting/wait_for_element_state.robot
=> Add custom message to Wait For Elements State and Wait For Function keywords

Browser/keywords/playwright_state.py, Browser/utils/__init__.py, Browser/utils/deprecated.py, atest/test/01_Browser_Management/video.robot, utest/test_deprecated.py
=> Add common way to deprecate arguments

Browser/keywords/waiter.py, atest/test/02_Content_Keywords/files.robot, node/playwright-wrapper/network.ts
=> Add support for suggestedFilename in Wait For Download keyword

Browser/keywords/waiter.py, atest/test/02_Content_Keywords/files.robot
=> Fix doc bug in Wait For Download keyword

Browser/keywords/evaluation.py, atest/test/06_Examples/open_in_another_tab.robot, node/playwright-wrapper/evaluation.ts, node/playwright-wrapper/grpc-service.ts, protobuf/playwright.proto
=> Download keyword should also return suggested file name

.github/workflows/on-release.yml, README.md, atest/docker/README.md
=> Fix pushing of :latest docker image, add docker pull instructions

Browser/keywords/cookie.py, atest/test/02_Content_Keywords/cookie.robot
=> Fix Add Cookie when Epoch is float like number

atest/test/01_Browser_Management/Auto_Closing/auto_closing.robot, node/dynamic-test-app/static/error.html, node/playwright-wrapper/playwright-state.ts
https://github.com/MarketSquare/robotframework-browser/issues/674
=> Fix blocking alert

Browser/keywords/network.py, yarn.lock
Content-Type and content-type are both same header.
=> Fix http header case

Browser/keywords/getters.py, atest/test/06_Examples/promised_cat_and_dog.robot, atest/test/variables.resource, node/dynamic-test-app/static/dogandcat.html
Fix missing @with_assertion_polling
=> Fix get text

Browser/keywords/browser_control.py
=> Update file name description in Take Screenshot documentation

atest/test/02_Content_Keywords/select_lists.robot, node/playwright-wrapper/getters.ts
Fixes https://github.com/MarketSquare/robotframework-browser/issues/757
=> add get selected options xpath support

Browser/base/librarycomponent.py, Browser/browser.py, Browser/keywords/browser_control.py, Browser/keywords/playwright_state.py
=> Remove ${OUTPUTDIR}/browser/ at suite startup

Browser/keywords/browser_control.py, atest/test/01_Browser_Management/timeout.robot
=> Calling Set Browser Timeout should not fail

Browser/keywords/playwright_state.py
=> Improve docs to provide link for http authentication

atest/test/06_Examples/open_in_another_tab.robot
=> Atest that download on page without URL navigation fails

Browser/keywords/playwright_state.py, Browser/utils/__init__.py, Browser/utils/data_types.py, atest/test/01_Browser_Management/record_har.robot
=> Har support

MANIFEST.in, setup.py
Hey folks! Thanks for maintaining this!
This PR just adds the LICENSE to the source distributions, as required by the terms of the `Apache-2.0` License. This is helpful for downstreams!
=> Add LICENSE to distributions

Browser/browser.py, Browser/requirements.txt
=> Read assertion operator table from assertion engine

Browser/keywords/evaluation.py
=> Document that Download keyword required valid html in active page

Browser/browser.py
Fix https://github.com/MarketSquare/robotframework-browser/issues/868
=> fix screenshot outside of test context

Browser/browser.py, Browser/utils/data_types.py
Fixes #819 at least partially, because from the docs it is really hard to understand how auto closing works
=> Improve autoclosing documentation

Browser/browser.py
=> Fixing inconsistent documentation for automatic closing

Browser/keywords/playwright_state.py, atest/test/01_Browser_Management/chromiun_channel.robot
=> Add support for channel in New Browser keyword

Browser/keywords/browser_control.py, atest/test/02_Content_Keywords/screenshot.robot, node/playwright-wrapper/browser-control.ts, protobuf/playwright.proto
Added **timeout**, **fileType** and **quality** arguments to **take_screenshot** #869
=> Take screenshot arguments

Browser/keywords/interaction.py
=> Improved Fill Secret keyword docs

Browser/keywords/playwright_state.py, atest/test/01_Browser_Management/playwright_state.robot, node/playwright-wrapper/playwright-state.ts, protobuf/playwright.proto, tasks.py
=> If context is created but browser does not exist, show log message to user

Browser/browser.py, Browser/requirements.txt
Add this: https://github.com/mkorpela/overrides
=> add overrides

Browser/keywords/evaluation.py, atest/test/03_Waiting/wait_for_function.robot, atest/test/05_JS_Tests/on_page_js.robot, node/playwright-wrapper/evaluation.ts
=> Fixed JS execution without element

Browser/keywords/getters.py, node/playwright-wrapper/getters.ts, utest/test_get_text.py
=> Sometimes element text can be empty

Browser/keywords/playwright_state.py, atest/test/01_Browser_Management/no_httpCredentials_logging.robot
=> Do not log httpCredentials for New Context Keyword

Browser/base/librarycomponent.py, Browser/keywords/interaction.py, Browser/keywords/playwright_state.py, atest/test/01_Browser_Management/no_httpCredentials_logging.robot, atest/test/02_Content_Keywords/text_keywords.robot, utest/test_secrets.py
=> Http credentials as secret

Browser/keywords/interaction.py, atest/test/02_Content_Keywords/dialogs.robot, node/playwright-wrapper/grpc-service.ts, node/playwright-wrapper/interaction.ts, protobuf/playwright.proto
=> Add support to verify and get alert text

Browser/keywords/playwright_state.py, utest/test_secrets.py
=> Actually use resolved secrets in New Context keyword

Browser/base/librarycomponent.py, atest/test/02_Content_Keywords/text_keywords.robot, utest/test_secrets.py
=> Improve secret resolving warning message

atest/test/02_Content_Keywords/test_record_selector.robot, node/playwright-wrapper/evaluation.ts, node/webpack.config.js, setup.py
=> add selector recorder tests

.github/workflows/on-push.yml, Browser/entry.py, atest/library/show_trace_tool.py, atest/test/01_Browser_Management/tracing.robot, atest/test/keywords.resource, atest/test/variables.resource, tasks.py
Fixes #1085 (at least on CI side)
=> test and fix show-trace in Windows OS

Browser/keywords/waiter.py, atest/test/03_Waiting/wait_for_element_state.robot
Fixes #1110
Also changes Wait For Function keyword with same bug
=> Fix Wait For Element State keyword with custom error and timeout

Browser/base/librarycomponent.py, Browser/keywords/playwright_state.py, atest/test/01_Browser_Management/storage_state.robot, node/playwright-wrapper/grpc-service.ts, node/playwright-wrapper/playwright-state.ts, protobuf/playwright.proto
=> Save storage state to file

Browser/requirements.txt
=> Update assertion engine to 0.1.0

Browser/keywords/getters.py, atest/test/02_Content_Keywords/basic_getters_ii.robot
=> Change Get Element State keyword assertion_expected argument default value to None

tasks.py
=> Add PW version section to release note generation

Browser/requirements.txt
=> Set RF 4.0.3 as minimum required RF version

Browser/keywords/promises.py
=> Fix Promise To Wait For Download keyword docs

Browser/keywords/browser_control.py
=> Improve Take Screenshot docs

Browser/keywords/browser_control.py, Browser/keywords/device_descriptors.py, Browser/keywords/evaluation.py
=> More docs fixes

Browser/browser.py, Browser/keywords/getters.py, atest/test/02_Content_Keywords/basic_getters.robot
=> Docs and test improvements

Browser/keywords/getters.py
=> More kw docs updates for getters

Browser/keywords/getters.py, Browser/keywords/promises.py, atest/test/02_Content_Keywords/invalid_assertions.robot, atest/test/02_Content_Keywords/keyboardInput.robot
=> Remove deprecated keywords

Browser/keywords/network.py, atest/test/03_Waiting/wait_for_http.robot
=> Improve Wait For Response docs and tests

Browser/keywords/interaction.py
=> Improve interaction keywords docs

Browser/keywords/interaction.py
=> Improve interaction keywords docs more

Browser/keywords/interaction.py
=> Improve keyword examples

Browser/keywords/network.py
=> Improve keyword examples for network

Browser/keywords/network.py
=> Docs updates 5

Browser/keywords/playwright_state.py
=> Improve PW state keywords

atest/test/__init__.robot, atest/test/keywords.resource, atest/test/variables.resource
Can be controlled by SYS_VAR_CLEAN variable
=> If test suite run has passed clean files

node/playwright-wrapper/static/selector-finder.js
=> small UI improvements for selector recorder

Browser/utils/data_types.py
Copy pasted from https://github.com/MarketSquare/robotframework-browser/pull/1285/files#diff-e9f55d32e197859755b0ce3d6950a4a1aea56661c70e9eb574e2ad80914854d0
=> Add docs string for RecordVideo datatype

Browser/keywords/strict_mode.py
=> Fix Set Stict Mode keyword docs

Browser/keywords/interaction.py
=> Fix Select Options By keyword docs

.github/workflows/on-push.yml, Browser/entry.py, README.md
=> Add rfbrowser clean-node command to delete wrapper folder

.github/workflows/on-push.yml
This reverts commit 74d87e5d72b2c16df71396db163ea71a9114f9a7.
=> Revert "Remove flaky test detection again"

Browser/keywords/browser_control.py, Browser/keywords/interaction.py
No coding changed, just docu for keywords
go_to
type_secret
select_options_by
drag_and_drop_by_coordinates
=> issue 1328 Docu keywords

Browser/gen_stub.py
=> Stub file generation fix for Python 3.10

Browser/browser.py, Browser/keywords/runonfailure.py, Browser/utils/data_types.py, atest/test/01_Browser_Management/run_on_failure.robot, utest/test_run_on_failure.py
=> Fix run on failure when using named args

Browser/keywords/cookie.py
Instead of warn use debug
Fixes #1406
=> Change cookie invalid expory logging

atest/test/03_Waiting/wait_for_element_state.robot, node/dynamic-test-app/static/waitfor.html, node/playwright-wrapper/evaluation.ts
Fixes #1442
Fixed by looking logs and code, because could not reproduce the problem
=> Fixes Wait For Element State with hidden state and when strict mode is False

Browser/keywords/interaction.py
=> Fix Select Options By docs

Browser/keywords/device_descriptors.py
Link in description was dead, I've updated it with new url
=> Update link to list of devices

atest/test/02_Content_Keywords/findLocator.robot, node/playwright-wrapper/playwright-invoke.ts
=> Counting elements withing frame is fixed

atest/test/02_Content_Keywords/findLocator.robot, node/playwright-wrapper/evaluation.ts
=> Get Elements should wait elements to be attached

Browser/__init__.py
=> Add missing data types to public API

atest/test/02_Content_Keywords/checkbox.robot, node/dynamic-test-app/static/waitfor.html, node/playwright-wrapper/interaction.ts
=> Fix random failure with Check/Uncheck Checkbox keyword

CONTRIBUTING.md, tasks.py
=> Generate old keyword docs from correct tag

Browser/dev-requirements.txt
See https://github.com/approvals/ApprovalTests.Python/issues/103
=> Pinn Approval tests untill running test gets fixed

atest/test/02_Content_Keywords/files.robot, utest/test_waiters.py
Need to figure out why these are failing, fix, and then merge
=> Start running upload files tests on windows

atest/test/03_Waiting/wait_for_http.robot, node/playwright-wrapper/network.ts
- Standardized urlOrPredicate handling
- Corrected grammar/spelling in waitForRequest log message.
- Added acceptance tests for URL, RegEx, and Predicate.
=> Fix wait for regex and predicate handling

atest/test/02_Content_Keywords/files.robot
Windows doesn't support dd, added platform check and changed Windows to use fsutil.
=> Update Generate Test File cmd to be OS dependent

node/playwright-wrapper/grpc-service.ts, node/playwright-wrapper/keyword-decorators.ts, node/playwright-wrapper/network.ts, node/tsconfig.json
=> Log when keywords calls method from node side

utest/test_python_usage.py
=> Create example how to use promise from Python

.github/workflows/on-push.yml, .github/workflows/on-release.yml, Browser/entry.py, docker/Dockerfile, tasks.py
Fix https://github.com/MarketSquare/robotframework-browser/issues/591
=> lock node side versions

package.json
=> Fix eslint for Windows

Browser/keywords/playwright_state.py, Browser/utils/__init__.py, Browser/utils/data_types.py, atest/test/01_Browser_Management/get_ids.robot, atest/test/01_Browser_Management/goto.robot, atest/test/01_Browser_Management/playwright_state.robot, atest/test/01_Browser_Management/video.robot, node/playwright-wrapper/keyword-decorators.ts
=> Return video path

Browser/keywords/crawling.py, node/dynamic-test-app/static/links/link1.html, node/playwright-wrapper/keyword-decorators.ts
Warn on error when goto fails in crawling (pass still)
=> Fix pdf crawling

Browser/keywords/getters.py
=> Document that Get Text also works with input and textarea elements

Browser/keywords/interaction.py, atest/test/02_Content_Keywords/select_lists.robot, node/playwright-wrapper/interaction.ts, protobuf/playwright.proto
=> Select Options By keyword should return options which was selected

node/playwright-wrapper/playwright-invoke.ts
=> For frames mo to use frameLocator

Browser/base/librarycomponent.py, Browser/browser.py, Browser/keywords/getters.py, Browser/keywords/playwright_state.py, Browser/keywords/webapp_state.py, Browser/requirements.txt, atest/test/02_Content_Keywords/assertions.robot, atest/test/variables.resource, node/dynamic-test-app/static/spaces.html
=> Assertion formatters

Browser/keywords/network.py
=> Fix Wait For Response docs

atest/test/02_Content_Keywords/focus.robot
=> Enabled focus tests back

Browser/entry.py
Also stores debug information from the environment
Fixes #1117
=> Store install info in log file

Browser/browser.py, Browser/keywords/getters.py, tasks.py
=> Fix get elements keyword docs

Browser/keywords/playwright_state.py
=> Change New Context acceptDownloads default value to True

Browser/base/librarycomponent.py, atest/test/02_Content_Keywords/text_keywords.robot
=> Fix empty usage for secret

Browser/requirements.txt
=> Raise minimum required RF version.

atest/test/01_Browser_Management/tracing.robot, atest/test/01_Browser_Management/video.robot, node/playwright-wrapper/playwright-state.ts
=> Fix creating trace file

node/dynamic-test-app/src/server.ts
=> Prepare for new grpc-js

Browser/base/librarycomponent.py, Browser/browser.py, Browser/keywords/interaction.py, Browser/utils/__init__.py, Browser/utils/data_types.py, atest/library/presenter_mode.py, atest/test/06_Examples/presenter_mode.robot, atest/test/keywords.resource, node/playwright-wrapper/interaction.ts
=> Allow config options for presenter mode

Browser/base/librarycomponent.py, Browser/keywords/getters.py, Browser/keywords/interaction.py
=> Add support for enable_presenter_mode for many getters keywords

Browser/keywords/interaction.py, atest/test/02_Content_Keywords/virtual_mouse.robot
Keyword can be used for Swipe actions which are very common on mobile.
=> added Drag And Drop Relative To

Browser/keywords/evaluation.py, atest/test/05_JS_Tests/on_page_js.robot, atest/test/06_Examples/js_evaluation.robot, node/playwright-wrapper/evaluation.ts, node/playwright-wrapper/grpc-service.ts, protobuf/playwright.proto
```robotframework
Evaluate Multiline JavaScript
${texts}=    Evaluate JavaScript    button
...    (elements, arg) => {
...      let text = []
...      for (e of elements) {
...        console.log(e.innerText)
...        text.push(e.innerText)
...      }
...      text.push(arg)
...      return text
...    }
...    all_elements=True
...    arg=${{[1,2,3]}}
Length Should Be    ${texts}    12
Should Be Equal    ${texts}[-1]    ${{[1,2,3]}}
```
=> New `Evaluate JavaScript` Keyword

atest/test/04_frames/frames_and_elements.robot, atest/test/variables.resource, node/dynamic-test-app/static/frames/frame_for_element_frame.html, node/dynamic-test-app/static/frames/frame_for_elements.html, node/playwright-wrapper/playwright-invoke.ts, tasks.py
=> Fix frames and get text with element

Browser/utils/data_types.py
username should be written in lower case
Fixes #1873
=> In proxy, change Username to username

Browser/keywords/playwright_state.py
=> Fix New Browser keyword headless argument doc

Browser/keywords/interaction.py, atest/test/02_Content_Keywords/checkbox.robot, atest/test/02_Content_Keywords/text_keywords.robot, atest/test/06_Examples/no_library_browser_found.robot, node/playwright-wrapper/interaction.ts, protobuf/playwright.proto, tasks.py
=> Force option for other intection keywords

Browser/browser.py, atest/test/05_JS_Tests/funky.js, atest/test/05_JS_Tests/jsextension.robot, node/playwright-wrapper/playwright-state.ts, tasks.py
Drafting JS translations for True == true, False == false, None == null..
=> Topic js <-> Python translation

Browser/dev-requirements.txt, Browser/keywords/browser_control.py, atest/library/screenshot.py, atest/test/02_Content_Keywords/screenshot.robot, atest/test/keywords.resource, node/playwright-wrapper/browser-control.ts, node/playwright-wrapper/grpc-service.ts, protobuf/playwright.proto, tasks.py
=> Added Playwright 1.20 features to `Take Screenshot`

atest/test/01_Browser_Management/no_httpCredentials_logging.robot, atest/test/02_Content_Keywords/screenshot.robot, tasks.py
Also skip no_httpCredentials_logging.robot in Mac
=> Fix robot linting

Browser/entry.py
=> Fix moves with caused by playwright-core

Browser/keywords/evaluation.py, Browser/keywords/getters.py, Browser/keywords/interaction.py, Browser/keywords/promises.py, node/playwright-wrapper/getters.ts
HTML Tables that do have the rows as direct children of the table element did not work.
=> fixed Table Bug

Browser/entry.py
=> Fix typo in rfbrowser command

.gitignore, Browser/entry.py, setup.py
=> Try Python logger for log file generation

Browser/base/librarycomponent.py, atest/test/02_Content_Keywords/basic_getters.robot, atest/test/06_Examples/presenter_mode.robot, atest/test/07_Failing/screenshot_on_failure.robot
=> Fix presenter mode

Browser/keywords/interaction.py, Browser/keywords/promises.py, atest/test/02_Content_Keywords/files.robot
Add tests and code for relative paths.
=> Topic relative upload paths

Browser/keywords/waiter.py, atest/library/same_keyword.py, atest/test/03_Waiting/wait_for_condition.robot
=> Keyword with same names should not raise an error with Wait For Condition

Browser/requirements.txt
=> Accept only AssertionEngine == 0.6.1

Browser/entry.py
=> Fix error when no access to write rfbrowser.log to install dir

Browser/base/librarycomponent.py, Browser/browser.py, Browser/entry.py, Browser/keywords/browser_control.py, Browser/keywords/cookie.py, Browser/keywords/crawling.py, Browser/keywords/evaluation.py, Browser/keywords/getters.py, Browser/keywords/playwright_state.py, Browser/keywords/promises.py, Browser/keywords/waiter.py, Browser/mypy.ini, Browser/utils/logger.py, Browser/utils/misc.py
=> Version in rfbrowser

Browser/browser.py, Browser/playwright.py
=> Add support for adding options for start node process

docs/plugins/README.md
=> Updated plugin documentation to be more readable.

atest/test/01_Browser_Management/get_empty_ids.robot, node/playwright-wrapper/evaluation.ts, package-lock.json
Fixes https://github.com/MarketSquare/robotframework-browser/issues/2598
=> reuse page recording functions if already called

Browser/base/librarycomponent.py, Browser/browser.py, Browser/keywords/browser_control.py, Browser/keywords/runonfailure.py, Browser/utils/settings_stack.py, atest/test/01_Browser_Management/timeout.robot, atest/test/08_Scope_Tests/Suite_1/Suite_1.1/Suite_1.1.3.robot, atest/test/08_Scope_Tests/scope_logger.py, atest/test/09_Plugins/ExamplePlugin.py, atest/test/09_Plugins/plugin.robot
- Scope can now be used more generically
- Scope can now be used from Plugins
- Scope of `Set Browser Timeout` is now fixed
- Listener API can now be used from Plugins (If new PLC is used)
=> Improved Scope Stack

.gitignore, Browser/base/librarycomponent.py, Browser/browser.py, Browser/entry.py, Browser/gen_stub.py, Browser/keywords/browser_control.py, Browser/mypy.ini, atest/test/01_Browser_Management/get_empty_ids.robot, atest/test/02_Content_Keywords/assertions.robot, atest/test/02_Content_Keywords/basic_getters.robot, atest/test/09_Plugins/ExamplePlugin.py, atest/test/09_Plugins/plugin.robot, tasks.py
Signed-off-by: René <snooz@posteo.de>
=> [Fixed #2570] Get code completion for LibraryComponent.library

Browser/base/librarycomponent.py, Browser/keywords/playwright_state.py, Browser/utils/data_types.py, atest/test/01_Browser_Management/get_empty_ids.robot, atest/test/01_Browser_Management/get_ids.robot, atest/test/01_Browser_Management/playwright_state.robot, atest/test/01_Browser_Management/playwright_state_getters.robot, atest/test/01_Browser_Management/reuse_existing_browsers.robot, atest/test/01_Browser_Management/switching_browsers.robot, atest/test/01_Browser_Management/tracing.robot, atest/test/02_Content_Keywords/checkbox.robot, atest/test/02_Content_Keywords/click.robot, atest/test/02_Content_Keywords/click_with_options.robot, atest/test/02_Content_Keywords/cookie.robot, atest/test/04_frames/deep_frames.robot, atest/test/06_Examples/js_evaluation.robot, atest/test/keywords.resource
Signed-off-by: René <snooz@posteo.de>
=> Implemented Reuse Existing Browsers (implements #1319)

Browser/gen_stub.py, Browser/keywords/getters.py, Browser/keywords/interaction.py, Browser/keywords/playwright_state.py, Browser/keywords/waiter.py, atest/library/screenshot.py, atest/test/02_Content_Keywords/basic_getters.robot, node/dynamic-test-app/src/login.tsx, node/playwright-wrapper/grpc-service.ts, node/playwright-wrapper/playwright-state.ts, node/playwright-wrapper/response-util.ts, protobuf/playwright.proto
=> initial implementation of Get Console Log and Get Page Errors (implements #2176)

.github/workflows/on-release.yml
This reverts commit 84450f294a71cc15d284cf04319b4ba5f48b95ca.
=> Revert "Bump docker/build-push-action from 1 to 4"

Browser/entry.py
=> Add --silent argument to suppress logging in init

Browser/entry.py
=> Add encoding to RotatingFileHandler

Browser/utils/data_types.py, atest/test/01_Browser_Management/no_httpCredentials_logging.robot
=> Fix HttpCredentials docs

Browser/browser.py, Browser/playwright.py, atest/test/01_Browser_Management/run_on_failure.robot
=> Add link to playwright-log.txt if keyword fails

Browser/utils/meta_python.py
Add support for RF 6.1, this at least causes issue https://github.com/robotframework/robotframework/issues/4538
Fixes #2785
=> Add support for RF 6.1

Browser/entry.py
=> Improve init error message

Browser/keywords/interaction.py, atest/test/02_Content_Keywords/tab.robot, node/playwright-wrapper/grpc-service.ts, node/playwright-wrapper/interaction.ts, protobuf/playwright.proto
=> Add Tab keyword

Browser/keywords/evaluation.py, atest/test/05_JS_Tests/on_page_js.robot, node/playwright-wrapper/evaluation.ts, protobuf/playwright.proto
Return number of highlighted elements and improve keyword docs
Fixes #2335
=> Enhance Highlight Elements

Browser/keywords/browser_control.py, Browser/utils/data_types.py, atest/test/02_Content_Keywords/screenshot.robot, node/playwright-wrapper/browser-control.ts
Add scale and maskColor args
Fixes #2854
=> Add missing args to Take Screenshot

.github/workflows/on-push.yml, .github/workflows/on-release.yml, download_file.py, tasks.py
=> Switch node 14 -> 16 in CI

atest/test/01_Browser_Management/playwright_state_getters.robot, node/playwright-wrapper/evaluation.ts, node/playwright-wrapper/interaction.ts
=> Supress locator.click: Target closed error

Browser/entry.py, tasks.py
=> Deprecate Python 3.7 support

.github/workflows/on-push.yml, Browser/pyproject.toml, setup.py, tasks.py
=> Drop support for Python 3.7

Browser/keywords/webapp_state.py, node/playwright-wrapper/evaluation.ts, node/playwright-wrapper/grpc-service.ts, protobuf/playwright.proto
Just removed the used old code of Execute JavaScript used by Session and Local Storage keywords.
=> Removed ExecJS code internally for Session/Local Storage keywords

node/playwright-wrapper/playwright-state.ts
=> added Webkit to New Persistent Context

Browser/browser.py, atest/test/02_Content_Keywords/findLocator.robot
=> set loglevel to info if screenshot could not be done because page was not open on failure

Browser/keywords/webapp_state.py, Browser/version.py, atest/test/05_JS_Tests/local_session_storage.robot, atest/test/variables.resource, docker/Dockerfile.latest_release, package-lock.json, package.json, setup.py
All keywords get an additional argument `frame_selector`.
If this points to an element inside an iframe, the SessionStorage of this frame is used.
This is particularly relevant if the iframe source has a different origin as the main page.
=> SessionStorage and LocaStorage keywords shall support frames from different orgigin.

Browser/browser.py, Browser/gen_stub.py, Browser/keywords/interaction.py, Browser/keywords/promises.py, Browser/utils/data_types.py, atest/test/01_Browser_Management/playwright_state_getters.robot, atest/test/02_Content_Keywords/basic_getters.robot, atest/test/02_Content_Keywords/checkbox.robot, atest/test/02_Content_Keywords/click_deprecated_options.robot, atest/test/02_Content_Keywords/findLocator.robot, atest/test/03_Waiting/wait_for_condition.robot, atest/test/03_Waiting/wait_for_element_state.robot, atest/test/08_Scope_Tests/Suite_1/Suite_1.1/Suite_1.1.3.robot, atest/test/08_Scope_Tests/scope_keywords.resource
Signed-off-by: René <snooz@posteo.de>
=> added Click With Options to deprecated ugly modifiers

Browser/browser.py, Browser/keywords/playwright_state.py, atest/test/01_Browser_Management/playwright_state.robot, node/playwright-wrapper/grpc-service.ts, node/playwright-wrapper/playwright-state.ts, protobuf/playwright.proto
=> Add runBeforeUnload option for close page

Browser/entry.py, Browser/requirements.txt, README.md, setup.py, tasks.py
Better argument handling and support for install individual browsers
Do with help of Python click
Fixes #3098
=> Better entry point

Browser/entry.py
=> Fix python -m Browser.entry

Browser/entry.py
Not all *nix platforms support forcing --with-deps
Fixes #3105
=> Fix rfbrowser init

Browser/entry.py
=> If can not log, catch error and continue

Browser/playwright.py
Fixes #3154
Or actually makes the problem go away
=> Fix, kind of macOS Sonoma problem

Browser/entry.py
=> Fix install log message

Browser/assertion_engine.py, Browser/base/librarycomponent.py, Browser/browser.py, Browser/keywords/__init__.py, Browser/keywords/formatter.py, Browser/keywords/getters.py, Browser/keywords/playwright_state.py, Browser/keywords/webapp_state.py, Browser/requirements.txt, Browser/utils/settings_stack.py, atest/library/common.py, atest/library/screenshot.py, atest/test/01_Browser_Management/run_on_failure.robot, atest/test/02_Content_Keywords/assertions.robot, utest/test_settings_stack.py
=> Assertion formatters should have scope

.github/workflows/on-push.yml, README.md, tasks.py
=> Drop Node 16 support

Browser/keywords/playwright_state.py
=> Remove hideRfBrowser and storageState from new_persistent_context keyword

Browser/base/librarycomponent.py, Browser/browser.py, Browser/playwright.py, Browser/utils/data_types.py
Will keep browser open also after test execution
Fixes #1263
=> AutoClosingLevel KEEP

Browser/entry.py, Browser/mypy.ini, Browser/playwright.py, tasks.py
=> Fix install logging message

Browser/keywords/runonfailure.py
Exaplain how Take Screenshot filename is determined
Fixes #1688
=> Improve Run On Failure documentation

Browser/browser.py, atest/test/01_Browser_Management/run_on_failure.robot
=> Fix named argument support in run on failure

Browser/keywords/playwright_state.py, atest/test/01_Browser_Management/playwright_state.robot, node/playwright-wrapper/playwright-state.ts
=> Video is not supported in remote browsers

Browser/keywords/interaction.py
=> Fix Click keyword docs

Browser/browser.py, atest/test/03_Waiting/wait_for_http.robot
=> Provide better tip on error cases

Browser/entry.py
=> Command line args fix for launch-browser-server

Browser/base/librarycomponent.py, utest/test_browser_folder_cleanup.py, utest/test_context_cache.py, utest/test_deprecated.py, utest/test_network.py, utest/test_presenter_mode_conversion.py, utest/test_python_usage.py, utest/test_run_on_failure.py, utest/test_secrets.py
=> Allow using httpCredentials from Python side

Browser/keywords/cookie.py, atest/test/01_Browser_Management/playwright_state.robot, utest/test_cookie.py
=> Fix cookie expiry

Browser/keywords/playwright_state.py
=> get_browser_catalog should log in debug level

Browser/keywords/waiter.py, Browser/utils/__init__.py, Browser/utils/data_types.py, atest/test/03_Waiting/wait_for_page_load_state.robot, node/playwright-wrapper/grpc-service.ts, node/playwright-wrapper/network.ts, protobuf/playwright.proto
=> Wait for page load state

Browser/keywords/network.py, Browser/keywords/waiter.py, Browser/utils/__init__.py, Browser/utils/data_types.py, atest/library/screenshot.py, atest/test/02_Content_Keywords/screenshot.robot, atest/test/03_Waiting/wait_for_page_load_state.robot, node/playwright-wrapper/grpc-service.ts, node/playwright-wrapper/network.ts, protobuf/playwright.proto
Improved docs and other things.
Fixes: #3327
=> USe correct Enum

Browser/keywords/browser_control.py, Browser/keywords/interaction.py, atest/test/02_Content_Keywords/screenshot.robot
=> Xray support

Browser/entry/__main__.py
=> Fix getting version

docker/Dockerfile.latest_release
This reverts commit 10906f2bb2c702434a764c522f08bf09f6df99dc.
Fixes #3603
=> Revert "shrink docker image a little"

Browser/entry/__main__.py
=> Fix windows rfbrowser init logging

docker/Dockerfile.latest_release
=> Fix docker release

docker/Dockerfile.latest_release
=> More fixed to docker

Browser/keywords/pdf.py
=> Explain that PDF works in Chromium headless

Browser/keywords/pdf.py, atest/test/02_Content_Keywords/pdf.robot
=> Fix Emulate Media type hints

Browser/entry/__main__.py
=> Support more browser in rfbrowser init

Browser/entry/__main__.py, Browser/requirements.txt
=> Use seedir for better folder walk

.github/workflows/on-push.yml, README.md, tasks.py
=> Try nodejs 22.x in CI

Browser/base/librarycomponent.py, Browser/browser.py, Browser/entry/__main__.py, Browser/entry/translation.py, Browser/keywords/browser_control.py, Browser/keywords/cookie.py, Browser/keywords/crawling.py, Browser/keywords/device_descriptors.py, Browser/keywords/formatter.py, Browser/keywords/getters.py, Browser/keywords/interaction.py, Browser/keywords/network.py, Browser/keywords/playwright_state.py, Browser/keywords/promises.py, Browser/keywords/waiter.py, Browser/mypy.ini, Browser/pyproject.toml, Browser/utils/data_types.py, Browser/utils/deprecated.py, Browser/utils/logger.py, Browser/utils/meta_python.py, Browser/utils/misc.py, Browser/utils/settings_stack.py, atest/test/02_Content_Keywords/assertions.robot
=> Convert to use native types for type hints

Browser/keywords/interaction.py, atest/test/02_Content_Keywords/dialogs.robot, atest/test/variables.resource, node/dynamic-test-app/static/two_dialogs.html, node/playwright-wrapper/grpc-service.ts, node/playwright-wrapper/interaction.ts, protobuf/playwright.proto, tasks.py
=> Handle multiple alerts with one promise

Browser/assertion_engine.py, Browser/keywords/network.py, Browser/requirements.txt, Browser/utils/data_types.py
=> Remove typing-extensions deps

atest/test/01_Browser_Management/playwright_state.robot, atest/test/02_Content_Keywords/files.robot
=> Generate Test Text Fil: optimize run time from 10 seconds to 2 seconds

Browser/keywords/network.py, atest/test/02_Content_Keywords/basic_getters.robot, atest/test/02_Content_Keywords/findLocator.robot, atest/test/03_Waiting/wait_for_http.robot, atest/test/05_JS_Tests/on_page_js.robot, atest/test/variables.resource, node/dynamic-test-app/src/login.tsx, node/dynamic-test-app/src/server.ts, node/playwright-wrapper/grpc-service.ts, node/playwright-wrapper/network.ts, node/playwright-wrapper/response-util.ts, protobuf/playwright.proto
=> Support bigger json responses

Browser/keywords/browser_control.py, atest/test/01_Browser_Management/reload.robot, node/playwright-wrapper/browser-control.ts, node/playwright-wrapper/grpc-service.ts, protobuf/playwright.proto
=> Add timeout and waitUntill args to reload keyword

Browser/keywords/getters.py, atest/test/02_Content_Keywords/basic_getters.robot
Fixes #3460
Also add test for it
=> Document how to use Get Property keyword for element html

docker/Dockerfile.latest_release
=> Remove not used packages from docker

Browser/keywords/clock.py, atest/test/01_Browser_Management/clock.robot
=> Change clock keyword names

Browser/base/librarycomponent.py, Browser/browser.py, Browser/keywords/coverage.py, atest/test/01_Browser_Management/coverage.robot, node/playwright-wrapper/coverage.ts
=> Make coverage alling to more other features

Browser/keywords/network.py, atest/library/certificate.py, atest/library/common.py, atest/library/os_wrapper.py, atest/library/screenshot.py, atest/library/show_trace_tool.py, atest/test/01_Browser_Management/keyword_banner.py, atest/test/01_Browser_Management/tracing_groups.py, atest/test/08_Scope_Tests/scope_logger.py, atest/test/09_Plugins/ExamplePlugin.py, atest/test/10_retest/mylib.py, package-lock.json, tasks.py, utest/robotframework_browser_translation_as_list/__init__.py, utest/robotframework_browser_translation_fi/__init__.py, utest/robotframework_browser_translation_not_working/__init__.py, utest/test_cookie.py, utest/test_network.py, utest/test_python_usage.py, utest/test_rfbrowser_translate.py, utest/test_translation.py
=> Fix responce json

Browser/entry/coverage_combine.py, atest/library/os_wrapper.py, atest/test/01_Browser_Management/coverage.robot
=> Fix coverage merging

Browser/keywords/network.py, package-lock.json, utest/test_network.py
=> Fix parsing network response

Browser/playwright.py
=> Increase node side server wait time

docker/Dockerfile.latest_release, docker/README.md, docker/atest/test.robot
=> Use playwright:v1.49.1-noble with Docker

Browser/browser.py, atest/test/02_Content_Keywords/basic_getters.robot, atest/test/02_Content_Keywords/basic_getters_expect_errors.robot, node/playwright-wrapper/getters.ts, package-lock.json
=> Update PW to 1.50.0

Browser/keywords/coverage.py, atest/test/01_Browser_Management/coverage.robot, node/playwright-wrapper/playwright-state.ts
=> Better logging if coverege config not found

atest/test/02_Content_Keywords/basic_getters.robot, atest/test/02_Content_Keywords/basic_getters_expect_errors.robot, node/dynamic-test-app/src/login.tsx, node/playwright-wrapper/getters.ts
=> Fix getting Get Element States after 19.2 release

docker/Dockerfile.latest_release
Also tune install process to use uv for speedup
=> Update docker playwright:v1.50.1-noble

.github/workflows/on-push.yml, Browser/browser.py, Browser/playwright.py, utest/test_translation.py
=> Python 3.13 support

Browser/utils/data_types.py, atest/test/02_Content_Keywords/click_with_options.robot
=> Support for ControlOrMeta KeyboardModifier

Browser/entry/__main__.py, Browser/entry/constant.py, Browser/entry/coverage_combine.py, Browser/entry/get_versions.py
=> Playwright version

Browser/browser.py, Browser/keywords/browser_control.py, Browser/keywords/clock.py, Browser/keywords/evaluation.py, Browser/keywords/interaction.py, Browser/keywords/locator_handler.py, Browser/keywords/network.py, Browser/keywords/pdf.py, Browser/keywords/waiter.py, Browser/playwright.py
Fixed some spelling errors in Browser and keyword documentation.
Fixes #4131
=> Fixed some spelling errors in the documentation

Browser/browser.py, Browser/keywords/browser_control.py, Browser/keywords/playwright_state.py, Browser/playwright.py, Browser/utils/logger.py, atest/test/01_Browser_Management/no_httpCredentials_logging.robot, atest/test/01_Browser_Management/playwright_state.robot, atest/test/01_Browser_Management/run_on_failure.robot, atest/test/01_Browser_Management/timeout.robot, atest/test/01_Browser_Management/video.robot, atest/test/02_Content_Keywords/assertions.robot, atest/test/02_Content_Keywords/checkbox.robot, atest/test/02_Content_Keywords/screenshot.robot, atest/test/02_Content_Keywords/text_keywords.robot, atest/test/09_Plugins/plugin.robot, tasks.py
=> Silence logging from outside keywods

Browser/keywords/interaction.py
=> Fixed Wait For Alert exemple in docs

Browser/browser.py
=> Fix rf5 support

Browser/keywords/playwright_state.py, node/dynamic-test-app/src/draggame.tsx, node/dynamic-test-app/src/login.tsx
=> Fix Get Console Log return type

Browser/keywords/browser_control.py, Browser/keywords/playwright_state.py, Browser/utils/logger.py
=> Fix LOGLEVEL in RF 6 or older

Browser/keywords/browser_control.py, utest/test_screenshot.py
=> take-screenshot-fix

Browser/keywords/cookie.py, atest/test/02_Content_Keywords/cookie.robot, utest/test_cookie.py
For #4257 
Should be fairly simple but do you think more tests are needed?
=> Support datetime for Add Cookie expiry

bootstrap.py
=> Fix bootstrap script

Browser/entry/__main__.py
=> Fix too long error outoput for folder init rfbrower init

Browser/entry/__main__.py, Browser/entry/install.py
=> Move install to own module

Browser/keywords/coverage.py, atest/test/01_Browser_Management/coverage.robot, atest/test/01_Browser_Management/coverageConfigInvalid.js, atest/test/01_Browser_Management/coverageConfigInvalid.txt, node/playwright-wrapper/evaluation.ts, node/playwright-wrapper/grpc-service.ts, node/playwright-wrapper/playwright-state.ts, protobuf/playwright.proto
=> Coverage as kw

.github/workflows/on-push.yml, tasks.py
=> NodeJS 24 support

browser_batteries/README.md
=> Improve BrowserBatteries README

docker/Dockerfile.latest_release
=> Docker image to PW 1.56.0
