Browser/browser.py
Browser/keywords/getters.py
Browser/keywords/playwright_state.py
Browser/utils/__init__.py
Browser/utils/meta_python.py
atest/test/01_Browser_Management/playwright_state.robot
atest/test/01_Browser_Management/playwright_state_getters.robot
atest/test/02_Content_Keywords/cookie.robot
atest/test/02_Content_Keywords/dialogs.robot
atest/test/03_Waiting/__init__.robot
node/playwright-wrapper/playwright-state.ts
utest/test_python_usage.py

Closes #284
For pages there's still some bugs left to squash.
Also design input required: Now that we don't anymore have numerical indexes, workflows like `Close Page  1  ALL  ALL` wouldn't make sense anymore since all indices are unique to the specific pages. Flows like `Close Page  ALL  ALL  CURRENT` could still be supported but closing all pages in all contexts without closing the contexts seems a bit nonsensical.

Mostly working ALL enum support

---

Browser/browser.py

Fixes an issue under the "Pages" section
It looks like the top part of the example, *** TestCases *, is outside of the code block and truncated.

Minor correction - removed special characters within code example

---

Browser/keywords/interaction.py
atest/test/02_Content_Keywords/text_keywords.robot

Secret can be visible, but it depends on logging. 
Fixes #421

Fix fill and type secret keyword docs

---

Browser/keywords/interaction.py
atest/test/02_Content_Keywords/text_keywords.robot

Use env variables to hold secrets in `Type Secret` and `Fill Secret` keywords.
Syntax is the following: `Type Secret  selector  %MY_ENV_VARIABLE`
Env variable name is prefixed with `%`.

Secrets with env variables

---

README.md

Installation of Browser fails (and is not supported currently) on Node.JS version >= 15. 
This was already [discussed on Slack](https://robotframework.slack.com/archives/C015KB1QSDN/p1608043930266600). 
Please add this important fact to the installation instructions of browser.

Add Node version limitation hint to the installation notes

---

Browser/keywords/interaction.py

So that it is easier to understand when keyword should be called.
Fixes #657

Update Handle Future Dialogs keyword docs

---

Browser/keywords/interaction.py

Typo at the Click keyword. In arguments it says clickCount in the documentation click_count, clickCount is accepted in the keyword

fixed typo in click documentation

---

Browser/browser.py
Browser/playwright.py
tasks.py
utest/test_python_usage.py

This PR fixes #1033 
Rundown of changes:
- Register Playwright `close` method to run on Python process exit
- Change `close` logic to always kill its subprocess, even if grpc throws an exception
- Change cached property access to not accidentally spawn a server on close
- Remove now superfluous listener method to not call `close` twice per process (which is ok but pointless)
Wasn't exactly sure where to put the atexit call, but in general it should be as late as possible because the registered methods are executed in LIFO order and we want our low-level stuff to still be available, but it also should always run even if something unexpected throws.

Close playwright process on exit

---

atest/test/04_frames/deep_frames.robot
node/playwright-wrapper/playwirght-invoke.ts

determineElement was not doing frame piercing correctly.
This is used in:
Take Screenshot,
Execute Javascript,
Wait For Function,
Get Bounding Box

Fix frame piercing selectors

---

Browser/keywords/network.py

in method ``wait_for_navigation``, parameter is ``wait_until`` instead of ``waitUntil`` as per documentation

typo in the parameter name

---

atest/test/06_Examples/open_in_another_tab.robot

If this works, single test failures in `Test.06 Examples.Open In Another Tab` should actually only fail a single test, and not 3 tests when the failures happen.

Add proper test setup and teardown to use clean browsers in 06_Examples/open_in_another_tab.robot

---

Browser/keywords/device_descriptors.py

Link to playwright list of devices was dead, I've replaced it with the correct one (I already replaced in in a previous PR, but the links was appearing twice, here I'm updating the second dead link)

update dead link

---

Browser/browser.py
Browser/keywords/playwright_state.py
node/playwright-wrapper/playwright-state.ts
node/playwright-wrapper/response-util.ts
package.json
protobuf/playwright.proto

A take on the documentation of JS side extension keywords.
`python -m robot.libdoc Browser::jsextension=tmp/my.js show Myfunc`
And showing:
```
Myfunc
------
Arguments:  [*args]
This is a function.
```
With tmp/my.js
```JavaScript
function myfunc() {
return 'hello';
}
myfunc.rfdoc = `
This is a function.
`;
function otherfunc() {
return 1;
}
otherfunc.rfdoc = `
This is another function.
`;
function thirdfunc() {
return 33;
}
exports.__esModule = true;
exports.myfunc = myfunc;
exports.otherfunc = otherfunc;
exports.thirdfunc = thirdfunc;
```

JS side keyword docs

---

atest/test/01_Browser_Management/tracing.robot

Skip trace viewer in Windows

---

atest/test/06_Failing/custom_failure_screenshot.robot
atest/test/06_Failing/screenshot_on_failure.robot

Should let STDOUT / CI logs be a little less misleading, by avoiding having FAIL's there

Use Run keyword and expect error for failure screenshot tests instead of StatusChecker

---

Browser/keywords/interaction.py

With this code
```
from Browser import Browser
browser = Browser()
browser.new_page("https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select")
browser.select_options_by("css=iframe.interactive >>> css=#pet-select", "label", "Cat")
```
A type error happens, because the "label" argument should be `SelectAttribute["label"]` instead.
The PR improved this hard-to-read error: 
```
Traceback (most recent call last):
File "/Users/kerkko/Code/robotframework-browser/Browser/playwright.py", line 149, in grpc_channel
yield playwright_pb2_grpc.PlaywrightStub(self._channel)
File "/Users/kerkko/Code/robotframework-browser/Browser/keywords/interaction.py", line 634, in select_options_by
response = stub.SelectOption(
File "/Users/kerkko/Code/robotframework-browser/.venv/lib/python3.9/site-packages …
```

Improve error in case of invalid type SelectAttribute is given to select_options_by

---

atest/test/02_Content_Keywords/select_lists.robot
node/dynamic-test-app/static/prefilled_email_form.html
node/playwright-wrapper/interaction.ts

But out code assumes so
Fixes #1622

Not all select elements has value attribute

---

atest/test/02_Content_Keywords/select_lists.robot
node/dynamic-test-app/static/prefilled_email_form.html
node/playwright-wrapper/interaction.ts
package-lock.json
package.json

Fix select options by

---

Browser/browser.py

Dict can be used to define the style attributes of the border

Explain that enable_presenter_mode also support dict

---

Browser/browser.py
utest/test_browser_folder_cleanup.py

Do outputdir/Browser folder cleanup only at suite startup

---

Browser/keywords/playwright_state.py

Examples of Close Page now better reflects contexts and browser are not closed when using close page.

altered examples of Close Page

---

Browser/base/librarycomponent.py
Browser/browser.py
atest/test/07_Failing/screenshot_on_failure.robot
tasks.py
utest/test_browser_folder_cleanup.py

Cleans only subfolder created by the Browser library. Fixes #2134

Clean only subfolder from ouptut/browser folder

---

Browser/keywords/interaction.py

Updated the link to Playwright documentation for "press" that was linked under "Press Keys" keyword. I accidentally pull requested my own fork so that is why this is two commits. First time contributor. Hope that doesn't mess anything up.

Update documentation for "Press Keys" keyword.

---

Browser/browser.py
Browser/keywords/browser_control.py
Browser/keywords/interaction.py
atest/test/01_Browser_Management/keyword_banner.py
atest/test/01_Browser_Management/keyword_banner.robot
node/playwright-wrapper/evaluation.ts
node/playwright-wrapper/static/selector-finder.js

keyword call banner and secret handling

---

.github/workflows/on-push.yml

When dropping node 12 some accidental mistakes happened with the CI sharding configuration. This PR fixes them. (in the PR macOS no longer runs tests with (macos, node 16, python 3.9) three times, instead it correctly runs with node 16, macos and python[3.8, 3.9, 3.10])

Run macOS tests on different python versions in CI

---

atest/test/09_Plugins/Import_JS_and_JS_in_Python.robot
node/playwright-wrapper/playwright-state.ts

When using jsextensions it is not possible to also initialise another extension from python code as well.
In the future we could also support multiple extensions at the same time, to improve structure, but that has low priority.

Support of multiple JSExtensions being initialised

---

atest/test/09_Plugins/ExamplePlugin.py
node/playwright-wrapper/playwright-state.ts

With this change, the order of of arguments does not matter anymore and the api arguments do not have to be specified when called from python.

implemented named arguments

---

Browser/base/librarycomponent.py
Browser/browser.py
Browser/keywords/browser_control.py
Browser/keywords/getters.py
Browser/keywords/interaction.py
Browser/keywords/playwright_state.py
Browser/keywords/runonfailure.py
Browser/keywords/strict_mode.py
Browser/keywords/webapp_state.py
Browser/utils/data_types.py
atest/test/02_Content_Keywords/assertions.robot
node/playwright-wrapper/getters.ts
protobuf/playwright.proto

Get Style is now able to return any style property, not only those included in the dictionary.
Also Pseudo Elements are supported.
Also added:
- Added Scope to `Show Keyword Banner`
Also fixed:
- Fixed Logging issue with `Type/Fill Secret`
- Fixed Docs of Scope
- Fixed 'none' string issue with Assertions

Get Style with Pseudo Elements

---

Browser/keywords/browser_control.py
Browser/keywords/playwright_state.py
node/playwright-wrapper/playwright-state.ts

This fixes some issues with `New Persistent Context`
Arguments:
- `defaultBrowserType` has not been handled in the past. so handing over devices had no influence on the browser.
- `storageState` does not work for persistent context in Playwright. Therefore it will be removed.

added defaultBrowser and removed non functional args

---

node/playwright-wrapper/network.ts

Just to be perfectly clear, the code changes originate from @wvanasten from link below, I just implemented them on browser-library main branch and ran acceptance tests on them to make sure the changes don't introduce unexpected issues, not trying to take credit for the actual IP
https://github.com/wvanasten/robotframework-browser/tree/remote-download-save-as
Edit: 
This whole PR stems from issue #2615
https://github.com/MarketSquare/robotframework-browser/issues/2615
As mentioned in my comment in the link above, the changes don't introduce issues in any connected area and I tested the solution itself and found it to be working well when provided an absolute path to the desired saveAs directory

Add changes from @wvanasten

---

Browser/keywords/promises.py
atest/test/03_Waiting/promise_to.robot

positional arguments were just chosen by index, but on varargs the index stays same but more arguments to come.

fixed Promise To does not work with *args #3200

---

Browser/browser.py
Browser/playwright.py
Browser/utils/__init__.py
Browser/utils/data_types.py
utest/test_cookie.py
utest/test_python_usage.py

Not it is possible to prevent creation of playwright-log.txt. If playwright-log.txt exist, then epoch timestamp is added to the filename. Instead of playwright-log.txt use playwright-log-1234.txt 
Fixes #2968

Inproves the playwright-log.txt handling

---

Browser/browser.py
Browser/entry.py
Browser/keywords/playwright_state.py
Browser/playwright.py
atest/test/01_Browser_Management/new_page_should_not_timeout.robot
atest/test/01_Browser_Management/persistent_state.robot
atest/test/01_Browser_Management/playwright_state.robot
node/playwright-wrapper/grpc-service.ts
node/playwright-wrapper/playwright-state.ts
protobuf/playwright.proto

Three new features:
1. `Launch Browser Server` keyword to start a browser with one robot and connect to it with another.
2. `Close Browser Server` keyword to terminate this browser server.
3. `rfbrowser launch-browser-server` cli entry point to start a server.
example:
`rfbrowser launch-browser-server chromium headless=No port=9999 wsPath=chromium/one`
This will create a server on `ws://localhost:9999/chromium/one`

added keywords and entry to launch browser server

---

Browser/keywords/interaction.py

Added info level logging for the Click and Select Options By keywords. In cases where the arguments came from variables, the default log didn't show what was clicked / selected.
Disclaimer: I'm a n00b. Make sure I haven't done something that will crash when something is null or whatever.
Fixes #3510

Click and Select Options By logging

---

Browser/keywords/cookie.py

Fix Cookie documentation "expires" instead of "expiry".

---

Browser/keywords/network.py
utest/test_network.py

I don't really know why (because I didn't dig that deep), but sometime the response body that hits `_format_response` is `None`. If that happens, the behavior described in #3549 is seen. @nfaustin suggested, to send the body though `json.dumps` (which would convert `None` to `'null'` which is then readable by `json.loads`), but I think simply not transforming the body is a more lightweight solution.
Fixes #3549
Still of course there is the question, why the body is empty in a first place, because neither @nfaustin nor I really expect it to be empty. In my use case, there is an empty response to an OPTION request to the same URL, but I'm matching to the request method GET and am still facing the exception.

Handle empty response bodies

---

.github/workflows/dockers.yml
docker/Dockerfile.latest_release

improved (fixed) version of #3595
builds but doesn't test because since its a separate step it'd need to push somewhere.
you'd have to either export the docker image to an artifact and pull it in to the second step, or just merge the two things into a single flow
either-way ci it probably needs refactoring to:
build > test > publish
for ci (non release events) it could also probably be optimized for speed to not bother building non-amd64 images since qemu is slow and it needs to compile things

Shrink docker image a little

---

Browser/keywords/interaction.py

Tab and Click With Options keyword noWaitAfter argument is deprecated by Playwright.

---

Browser/browser.py
atest/test/00_Clean_Output_Dir/01_initial_import.robot
atest/test/05_JS_Tests/jsextension.robot
utest/test_python_usage.py

Browser().playwright is a property now and only initialised if a keyword is called or a JS extension is used.
start_stuite and start_test used it as well, but avoid it if possible.
This fixes issue #3757 and PR #3758

Playwright is a property now

---

docker/Dockerfile.latest_release
package-lock.json

Kudos to mkorpela for fix
Fixes  #3835

Fix docker to use Python 3.12

---

docker/Dockerfile.latest_release
docker/Dockerfile.tests
docker/README.md

Instead of using --break-system-packages for pip. Also removed double install of browser binaries
Fixes #4034

Use Python venv to install Browser library

---

Browser/playwright.py
Browser/utils/js_utilities.py

* calling os.listdir() to check if subdirectory exists could be slow
* round() already returns int if ndigits arg is omitted.

Fix ruff checks

---

Browser/entry/get_versions.py

The `rfbrowser --version` command give an error. Also regex didn't work work when a Playwright version was found through `npm list playwright`. 
**This change is only tested on Windows, since I don't have Linux or a Mac**

Fix for rfbrowser --version command for WIndows

---

Browser/browser.py
Browser/playwright.py
Browser/utils/misc.py
node/playwright-wrapper/index.ts

Using robotframework-browser within a VS Code devcontainer on a macOS host with --network host is not possible, since the binding when starting Playwright fails. However, when using 0.0.0.0 as host everything works as expected.
Therefore, this merge request makes the host when starting the playwright process configurable.
Fixes #4012

Make Playwright host configurable
